### ISSUE TITLE
SSL expired for domain https://de.openlegaldata.io/

### ISSUE THREAD

**Issue by haexhub** [openlegaldata/oldp#118]
hello team,

your ssl certificat for your [domain](https://de.openlegaldata.io/ ) is expired, since yesterday Tue, 09 Apr 2024 11:15:04 GMT.
Could you please renew it and maybe and ideally establish an automated process for this, if this is not already the case.

thank you very much and thanks for your project!

![grafik](https://github.com/openlegaldata/oldp/assets/29780781/64c44bcc-bd59-4fc8-ae56-4eebf87822e9)

**Comment by malteos** [comment]
Thanks for the notification!
