### ISSUE TITLE
Public Dockerfile

### ISSUE THREAD

**Issue by malteos** [openlegaldata/oldp#18]
Add Dockerfile to repo and make it available on Docker Hub.

- pipenv
- Dockerfile: gunicorn + django + npm
- docker-compose for services
  - nginx + letsencrypt (?)
  - mysql
  - es
  - redis
- Auto-build from git repo

**Comment by malteos** [comment]
WIP: https://hub.docker.com/r/openlegaldata/oldp

**Comment by abitrolly** [comment]
[Dockerfile](https://github.com/openlegaldata/oldp/blob/master/Dockerfile) is there. What is its status?

**Comment by malteos** [comment]
Dockerfile + docker-compose should work. Please reopen if there are any issues.
