### ISSUE TITLE
Improve site performance

### ISSUE THREAD

**Issue by malteos** [openlegaldata/oldp#3]
Currently loading the web page can take several seconds, making the site not user friendly. Thus, we should improve the site performance.

- [ ] Analyze SQL slow query log
- [ ] Use `db_index=True` for all query fields
- [x] Enable [Django's Memcached integration](https://docs.djangoproject.com/en/2.0/topics/cache/) (or redis)
- [x] Optimize Images
- [x] Bundle JS scripts
- _Import only JS from jQuery + Bootstrap that is actually used (not much of an effect -> not needed)_
- [x] Use `select_related()` to decrease number of db queries (don't use own `get_x()` methods)

**Comment by mschwarzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub](https://trello.com/c/5IcswCNj/2-github)

**Comment by mschwarzer** [comment]
- Use `select_related()` to decrease number of db queries

**Comment by mschwarzer** [comment]
- Use `select_related()` also for admin views.

**Comment by malteos** [comment]
Closing for now...
