### ISSUE TITLE
Error 500 using api search 

### ISSUE THREAD

**Issue by WUUUGI** [openlegaldata/oldp#39]
## Problem
When using `https://de.openlegaldata.io/api/cases/search/` or `https://de.openlegaldata.io/api/laws/search/` both return an error 500 with following message:

> Fehler 500
> 
> Webservice currently unavailable. Our service team has been dispatched to bring it back online.
>

## Expected
A valid list depending on the search query would be an expected response.

**Comment by malteos** [comment]
Thanks for reporting this issue. It seems that this is related to the search framework we are using (drf_haystack). I'll look into it in the next few days.

**Comment by malteos** [comment]
Sorry for the delay  @WUUUGI but now this is fixed as well in production.
