### ISSUE TITLE
API key Issue

### ISSUE THREAD

**Issue by ChrisChross** [openlegaldata/oldp#58]
When i try to call the API, i get the following error:

MaxRetryError: HTTPSConnectionPool(host='de.openlegaldata.io', port=443): Max retries exceeded with url: /api/courts/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Any idea how to enable requests?

**Comment by malteos** [comment]
Thanks for reporting this!

This was a server-side issue with the SSL certificate. Should be fixed by now.

**Comment by ChrisChross** [comment]
wow 😯  this was amazingly fast support! Thank you @malteos.

I have another request for you:
Do you think it is possible to make oldp-api available in pip or conda?
E.g. pip install oldpi-api (instead of downloading from github).

**Comment by malteos** [comment]
My regular job keeps me very busy so I won't be able to publish it on PyPi anytime soon. But you can also install Python packages directly from git (works in requirements.txt too):

`pip install git+https://github.com/...`

Even from specific branches: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch
